### PR TITLE
logp function using cholesky factor

### PR DESCRIPTION
**Pull request by bwengals**
Hi @jonathanhfriedman, I added a logp function that uses the Cholesky factor.  Tested the theano implementation locally against scipy.stats at it looked good.

I wonder if we should refactor the `get_tau_cov` function... I think it is only used by `MvNormal` and the adding `chol` makes it seem a bit awkward.

### CODE REVIEW

**Comment by jonathanhfriedman** [comment]
Currently, both `chol` and `tau` will always be defined. If the `chol` logp is faster/more stable, then we could just ignore `tau` and refactor `get_tau_chol()` to just give `chol`, which would make things cleaner.

**Comment by bwengals** [comment]
That's true.  We'll have to test it out.  Also, something to keep in mind while benchmarking, I noticed that theano's cholesky gradient, `perform` [(line 129 here)](https://github.com/Theano/Theano/blob/master/theano/tensor/slinalg.py) is likely pretty slow, with all the pure python loops.  A C or Cython implementation of this part of the op might make a huge difference and be good to include in the PR (and/or PR to theano?)

**Comment by jonathanhfriedman** [comment]
Great point about `perform`, and it doesn't look like a Cython version would be too hard to implement either.

**Comment by jonathanhfriedman** [comment]
Actually, I'm not that familiar with the inner workings of Theano, but it looks `Cholesky` implements its own more optimized `grad` method instead of referencing `CholeskyGrad` at all (versus `Eigvalsh` which calls `EigvalshGrad` in its `grad`). Does `CholeskyGrad` do anything?

**Comment by bwengals** [comment]
Yeah, your right!  That's interesting.  They don't look like the same algorithm at all either.  `CholeskyGrad` has that reference to a paper next to it too.  I was going to raise an issue but found [this first](https://github.com/Theano/Theano/pull/4148).  Very related, they get into some of the implementation and speed issues for GPs.  I'm going to spend some time giving this stuff a close look.

**Pull request merged**
